version: "3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build:
      context: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpack
    volumes:
      - .:/myapp
    links:
      - webpack
    ports:
      - "3000:3000"
    depends_on:
      - db
      - webpack
  webpack:
   build:
     context: .
   command: bin/webpack-dev-server
   volumes:
     - .:/myapp
   ports:
     - '3035:3035'
   environment:
     NODE_ENV: development
     RAILS_ENV: development
     WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
